services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./index.js:/app/index.js

  mongodb:
    image: mongo:8.0
    ports:
      - "27017:27017"
    entrypoint: ["mongod", "--bind_ip_all", "--replSet", "rs0"]

  mongodb-setup:
    image: mongo:8.0
    restart: on-failure
    volumes:
      - ./setup.sh:/scripts/setup.sh
    entrypoint: ["/scripts/setup.sh"]
    depends_on:
      - mongodb

  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_URL=mongodb://mongodb/temp
      - PORT=8082
    ports:
      - "8082:8082"
    restart: unless-stopped
    depends_on:
      - mongodb
